### ISSUE TITLE
I will add number system  and currency conveter to it, making it more functional

### ISSUE THREAD

**Issue by hansikasharma** [VinnuReddy18/Calculator#5]
Adding these features will increase the functionality of tis calculator please assign me the issue, I am willing to work

**Comment by VinnuReddy18** [comment]
> Adding these features will increase the functionality of tis calculator please assign me the issue, I am willing to work

Sure Hansika. Go on and let me know if you are doing projects. Im willing to work too.Thank You.
My linkedin : https://www.linkedin.com/in/vinay-kumar-reddy-161896287/

**Comment by narasimha-1511** [comment]
Hey is she wroking on the issue or can i work on this ??

**Comment by VinnuReddy18** [comment]
@hansikasharma Whats the status of issue?
