### ISSUE TITLE
Add finding square root and power of number button

### ISSUE THREAD

**Issue by hrishi-singh** [VinnuReddy18/Calculator#9]
Add scientific calculator features button, like finding square root, cube root, log etc.

**Comment by VinnuReddy18** [comment]
Go on @hrishi-singh

**Comment by VinnuReddy18** [comment]
Any update on work @hrishi-singh ??

**Comment by hrishi-singh** [comment]
I have added it , also  suggest you ,not to use inbulit eval function to solve expression as it is not a good practice to use eval function , also eval function was not able to identify square root and power symbol ,therefore, it is better to use regex. i was implimented it to solve expression use regex, which is apart from solving regular expression , it is also able to evaluate power and square root present in the function.
